### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by abetusk** [zzarcon/microm#13]
Was the intent to have `microm` be under a GPL compatible license of some sort?  Could you post a license file if so?

**Comment by zzarcon** [comment]
@abetusk sorry, I forgot! is now here https://github.com/zzarcon/microm/blob/master/LICENSE

Thanks!

**Comment by abetusk** [comment]
Thank you!  Looks like an awesome library!

**Comment by zzarcon** [comment]
@abetusk thanks you liked man! :dancers:
