### ISSUE TITLE
Demo doesn't work in Chrome 47

### ISSUE THREAD

**Issue by philfreo** [zzarcon/microm#16]
Cool library idea. I gave [the demo](http://zzarcon.github.io/microm/) a shot in OS X Chrome Version 47.0.2526.80 (64-bit) and recording didn't work. I see "error recording" in the console.

Ideas?

**Comment by zzarcon** [comment]
@philfreo true, that's quite critical, thanks for the report, I'll take a look now!

**Comment by zzarcon** [comment]
@philfreo just did a quick check and seems that this is the problem https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

The library works fine when the files are in the same domain, just I have to fix this for the demo. :)

**Comment by adrianblynch** [comment]
Make the link secure and it starts working again:

https://zzarcon.github.io/microm/

**Comment by zzarcon** [comment]
@adrianblynch done! Thanks you so much for the help.

**Comment by adrianblynch** [comment]
Well thanks for your work on this project!

I have a use case in mind for work.

**Comment by philfreo** [comment]
Cool, thanks. You should update your link in the Repo URL from `https://zzarcon.github.io/microm` (without trailing slash) to `https://zzarcon.github.io/microm/` (with trailing slash) because without it, it actually redirects back to the non-https version.

**Comment by zzarcon** [comment]
@philfreo good point, changed now, thanks you!
