### ISSUE TITLE
Is it possible to record sound created by browser using this library ? 

### ISSUE THREAD

**Issue by shivrajsa** [zzarcon/microm#21]
I have a music application where user can write & play music, I am wondering if I can use this library to record the music played by browser & export it. is it possible to do that using this library. Please help

**Comment by benlinton** [comment]
Yes, this library will allow you to record and export in Chrome and Firefox.

**Comment by shivrajsa** [comment]
@benlinton Could you please share code example to achieve that?

**Comment by benlinton** [comment]
Sure, I'll try to get to this soon.
